### ISSUE TITLE
Targeting html in CSS

### ISSUE THREAD

**Issue by griffinlacek** [wim-vr/prj-rev-bwfs-dasmoto#3]
Nothing wrong with using html to set font-family for the page, but body is often used instead as it directly influences children elements. Here's a good discussion on this: https://css-tricks.com/html-vs-body-in-css/

https://github.com/wim-vr/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/resources/css/style.css#L10-L12

**Comment by wim-vr** [comment]
Thank you for the hint!
The discussion you mentioned was worth reading.
